artifacts_root: artifacts

# Data Ingestion Configuration
data_ingestion:
  root_dir: artifacts/data_ingestion
  raw_data_dir: artifacts/data_ingestion/raw
  processed_data_dir: artifacts/data_ingestion/processed
  
  # OpenF1 API Configuration
  api:
    base_url: https://api.openf1.org/v1
    timeout: 30
    max_retries: 3
    batch_size: 1000
  
  # Target all 2025 race weekends
  target_meetings:
    - meeting_key: "latest"
    - meeting_key: "1253"  # Pre-Season Testing
    - meeting_key: "1254"  # Australian Grand Prix
    - meeting_key: "1255"  # Chinese Grand Prix
    - meeting_key: "1256"  # Japanese Grand Prix
    - meeting_key: "1257"  # Bahrain Grand Prix
    - meeting_key: "1258"  # Saudi Arabian Grand Prix
    - meeting_key: "1259"  # Miami Grand Prix
    - meeting_key: "1260"  # Emilia Romagna Grand Prix
    - meeting_key: "1261"  # Monaco Grand Prix
    - meeting_key: "1262"  # Spanish Grand Prix
    - meeting_key: "1263"  # Canadian Grand Prix
    - meeting_key: "1264"  # Austrian Grand Prix
  
  # Sessions to ingest for each meeting
  sessions_to_ingest:
    - "Practice 1"
    - "Practice 2" 
    - "Practice 3"
    - "Qualifying"
    - "Sprint"
    - "Race"
  
  # Endpoints to ingest
  endpoints:
    - "meetings"
    - "sessions"
    - "drivers"
    - "laps"
    - "pit"
    - "stints"
    - "position"
    - "intervals"
    - "weather"
    - "race_control"

# Data Validation Configuration
data_validation:
  root_dir: artifacts/data_validation_pre_post
  validation_report_dir: artifacts/data_validation_pre_post
  data_quality_threshold: 0.95
  missing_value_threshold: 0.1
  outlier_threshold: 3.0
  validate_raw_data: true
  validate_transformed_data: true
  generate_validation_report: true
  save_validation_results: true
  validation_report_format: json
  tables_to_validate:
    - "sessions"
    - "drivers"
    - "laps"
    - "pit_stops"
    - "stints"
    - "positions"
    - "intervals"
    - "weather"

# Data Transformation Configuration
data_transformation:
  missing_value_strategy: impute  # impute, drop, interpolate
  outlier_strategy: context_aware  # context_aware, remove_system_errors, cap, ignore
  outlier_threshold: 3.0
  create_tire_features: true
  create_lap_features: true
  create_weather_features: true
  create_driver_features: true
  numeric_columns:
    - "lap_duration"
    - "duration_sector_1"
    - "duration_sector_2"
    - "duration_sector_3"
    - "pit_duration"
    - "lap_start"
    - "lap_end"
    - "tyre_age_at_start"
    - "position"
    - "gap_to_leader"
    - "interval"
    - "air_temperature"
    - "track_temperature"
    - "humidity"
  categorical_columns:
    - "compound"
    - "flag"
    - "category"
    - "scope"
  datetime_columns:
    - "date_start"
    - "date_end"
    - "date"
  tables_to_transform:
    - "sessions"
    - "drivers"
    - "laps"
    - "pit_stops"
    - "stints"
    - "positions"
    - "intervals"
    - "weather"